import Head from "next/head";

import { Layout } from "../components";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Crypto JO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main
          className="w-full h-screen bg-jo-600 rounded-tl-3xl
        before:block before:absolute before:w-full before:h-full before:left-0 before:bg-jo-800 before:-z-10"
        ></main>
      </Layout>
    </div>
  );
}
